sonar.projectKey=memaix
sonar.projectName=Memaix
sonar.projectVersion=1.0

sonar.sources=gateway/src,login-app
sonar.exclusions=**/tests/**,**/__pycache__/**,**/.venv/**,**/node_modules/**,**/*.pyc

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
