sonar.projectKey=memaix
sonar.projectName=Memaix

sonar.sources=gateway/src,login-app
sonar.exclusions=**/tests/**,**/__pycache__/**,**/.venv/**,**/node_modules/**,**/web-tests/**,**/*.pyc

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=gateway/web-tests/coverage/lcov.info
